version: '3.8'

services:
  redis:
    image: redis:7
    command: >
      redis-server
        --appendonly yes
        --appendfsync everysec
        --auto-aof-rewrite-percentage 100
        --auto-aof-rewrite-min-size 64mb
        --loglevel warning
    ports:
      - "6379:6379"  
    volumes:
      - redis-data:/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:latest
    ports:
      - "27016:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network

  # prolog-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.prolog
  #   ports:
  #     - "4241:4242"
  #   volumes:
  #     - ./pl:/app/pl
  #     - /mnt/hdd_1/abdu/prolog_out_v2:/mnt/prolog_out_v2
  #     - /mnt/hdd_1/abdu/prolog_out_v3:/mnt/prolog_out_v3
  #   networks:
  #     - app_network

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5008:5000"
    environment:
      - FLASK_ENV=development
      - PREFECT_API_URL=http://prefect-service:4200/api
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/app/data
      # - /mnt/hdd_1/rediet/hypothesis-generation-demo/data:/app/data/external_data  
    depends_on:
      - mongo
      - redis 
      # - prolog-service
      - prefect-service
    command: >
      sh -c "
      python main.py --ensembl-hgnc-map data/ensembl_to_hgnc.pkl --hgnc-ensembl-map data/hgnc_to_ensembl.pkl \
      --go-map data/go_map.pkl --swipl-host prolog-service --swipl-port 4242 
      "
    networks:
      - app_network

  prefect-service:
    build:
      context: .
      dockerfile: Dockerfile.prefect
    ports:
      - "4201:4200"
    volumes:
      - .:/app
      - prefect-data:/root/.prefect 
    environment:
      - PREFECT_API_URL=http://localhost:4200/api
    env_file:
      - .env
    command: > 
      sh -c "prefect server start --host 0.0.0.0"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  prefect-deployment:
    build:
      context: .
      dockerfile: Dockerfile.prefect
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "
      python deployments.py --ensembl-hgnc-map /app/data/ensembl_to_hgnc.pkl 
      --hgnc-ensembl-map /app/data/hgnc_to_ensembl.pkl 
      --go-map /app/data/go_map.pkl 
      --swipl-host prolog-service 
      --swipl-port 4242
      "
    environment:
    - PREFECT_API_URL=http://prefect-service:4200/api
    - REDIS_URL=redis://redis:6379/0
    depends_on:
      prefect-service:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app_network

volumes:
  mongo-data:
  prefect-data:
  redis-data: 

networks:
  app_network:
    driver: bridge